version: "2"
services:
  db:
    image: hylee42/cloudflask-db:v1.0.5
    ports:
      - "3306:3306"

  app:
    links:
      - db
    image: hylee42/cloudflask:v1.0.12
    ports:
      - "5000:5000"
    environment:
      MYSQL_HOST: localhost
      MYSQL_USER: root
      MYSQL_PASSWORD: mysecret
      MYSQL_DB: daily_quiz
