version: "2"
services:
  db:
    container_name: my-mariadb
    image: hylee42/cloudflask-db:latest
    ports:
      - "3306:3306"
  app:
    links:
      - db
    env_file:
      - env.list
    image: hylee42/cloudflask:latest
    ports:
      - "8080:8080"
